;#########################
;#####   ESP32 Dev   #####
;#########################

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -D OLED_WIDTH=128
    -D OLED_HEIGHT=64
    -D OLED_SDA=21
    -D OLED_SCL=22
    -D OLED_RST=-1
    -D OLED_DRIVER_SSD1306
    -D CORE_DEBUG_LEVEL=0
    -D TOUCH_PIN=4
    -D OLED_I2C_ADDR=0x3C
    -O2

lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson@^7.2.2
    adafruit/Adafruit SSD1306@^2.5.17
    arduino-libraries/Arduino_JSON@^0.2.2


;##################################
;#####   ESP32 S3 ZERO        #####
;##################################


[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

board_build.partitions = default.csv

build_flags =
    -I include
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

    -D OLED_WIDTH=128
    -D OLED_HEIGHT=64
    -D OLED_SDA=13
    -D OLED_SCL=12
    -D OLED_RST=-1
    -D OLED_DRIVER_SSD1306
    -D CORE_DEBUG_LEVEL=0
    -D TOUCH_PIN=11
    -D OLED_I2C_ADDR=0x3C

monitor_speed = 115200
upload_speed = 921600
lib_deps =
    olikraus/U8g2
    adafruit/Adafruit SSD1306@^2.5.17
    arduino-libraries/Arduino_JSON@^0.1.0
    bblanchon/ArduinoJson@^7.2.2