; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	moononournation/GFX Library for Arduino@^1.6.7
	olikraus/U8g2
	adafruit/Adafruit SSD1306@^2.5.17
	arduino-libraries/Arduino_JSON@^0.2.2
	bblanchon/ArduinoJson@^7.2.2
build_flags = 
	-D OLED_WIDTH=128
	-D OLED_HEIGHT=64
	-D OLED_SDA=21
	-D OLED_SCL=22
	-D OLED_RST=-1
	-D OLED_DRIVER_SSD1309
	-DCORE_DEBUG_LEVEL=0
	-O2
	-D TOUCH_PIN=4
	-D OLED_I2C_ADDR=0x3C
